<footer>
    <ul>
        <li>Lorem</li>
        <li>Ipsum</li>
        <li>Dolore</li>
        <li>Cogito</li>
    </ul>
    <ul>
        <li>Lorem</li>
        <li>Ipsum</li>
        <li>Dolore</li>
        <li>Cogito</li>
    </ul>
</footer>